apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-app
spec:
  selector:
    matchLabels:
      app: fastfood
  template:
    metadata:
      labels:
        app: fastfood
    spec:
      initContainers:
      - name: wait-for-postgres
        image: postgres:17-alpine
        command: ['sh', '-c', '
          echo "Aguardando o postgres ficar pronto...";
          until pg_isready -h postgres -p 5432; do
            echo "Ainda aguardando...";
            sleep 2;
          done;
          echo "Postgres está pronto!";']
      containers:
        - name: fastfood
          image: srteixeiradias/fastfood:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-secret
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
          livenessProbe:
            httpGet:
              path: /api/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 5
            failureThreshold: 3