apiVersion: v1
kind: Service
metadata:
  name: fastfood-service
  namespace: fastfood 
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: fastfood
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer