name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  infra:
    uses: ./.github/workflows/terraform-infra.yaml
    with:
      environment: release
      aws-region: sa-east-1
      aws-statefile-s3-bucket: "soat-project-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "soat-project-sa-east-1-terraform-lock"
    secrets:
      AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}

  kubernetes:
    needs: infra
    uses: ./.github/workflows/terraform-kubernetes.yaml
    with:
      environment: release
      aws-region: sa-east-1
      aws-statefile-s3-bucket: "soat-project-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "soat-project-sa-east-1-terraform-lock"
    secrets:
      AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
