name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  infra:
    uses: ./.github/workflows/terraform-infra.yaml
    with:
      environment: prod
      aws-region: sa-east-1
      aws-statefile-s3-bucket: "soat-project-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "soat-project-sa-east-1-terraform-lock"
    secrets:
      AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}

  kubernetes:
    needs: infra
    uses: ./.github/workflows/terraform-kubernetes.yaml
    with:
      environment: prod
      aws-region: sa-east-1
      aws-statefile-s3-bucket: "soat-project-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "soat-project-sa-east-1-terraform-lock"
    secrets:
      AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      RDS_ENDPOINT: ${{ secrets.RDS_ENDPOINT }}
      MP_TOKEN: ${{ secrets.MP_TOKEN }}
      COLLECTOR_ID: ${{ secrets.COLLECTOR_ID }}
      POS_ID: ${{ secrets.POS_ID }}

  echo:
    needs: kubernetes
    uses: ./.github/workflows/echo-endpoints.yaml
    with:
      environment: release
      aws-region: sa-east-1
    secrets:
      AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
