name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  infra:
    uses: ./.github/workflows/terraform.yaml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::783906943381:role/github-actions-soat-project-pipeline"
      aws-region: sa-east-1
      aws-statefile-s3-bucket: "soat-project-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "soat-project-sa-east-1-terraform-lock"

  kubernetes:
    needs: infra
    uses: ./.github/workflows/terraform-kubernetes.yaml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::783906943381:role/github-actions-soat-project-pipeline"
      aws-region: sa-east-1
      aws-statefile-s3-bucket: "soat-project-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "soat-project-sa-east-1-terraform-lock"
